export function renderDrawer(): string {
  return `
<div class="drawer bp-boot" id="drawer">
<div class="drawer-body">
<section class="card replay" data-panel="replay"><div class="panel-head"><span class="panel-title">Trials &amp; Replay</span><span class="panel-meta" id="trial">SEED 42 · VISUAL · INTACT</span></div><div class="replay-grid"><div><h3>RUN A TRIAL</h3><div class="replay-form"><label>Task<select id="task"></select></label><label>Brain<select id="ablation"><option value="none">Intact</option><option value="zero">Zeroed features</option><option value="sensory">Vision silenced</option><option value="shuffle">Shuffled features</option></select></label><label>Seed<input id="seed" type="number" value="1000" min="0" step="1"></label><button id="run" class="primary">Run trial</button></div><p id="outcome" class="outcome">Outcome: —</p></div><div><h3>REPLAY AN EVALUATION</h3><div class="replay-form"><label>Report<select id="report"><option value="">No reports loaded</option></select></label></div><p id="report-summary" class="outcome"></p><div id="seeds" class="seed-grid" aria-label="Evaluation seeds"></div></div></div></section>
<section class="card brain-card" data-panel="brain" hidden><div class="panel-head"><span class="panel-title">Neuron Inspector</span></div><div class="inspect"><select id="neuron" aria-label="Neuron to inspect"><option>Loading neurons…</option></select><div class="button-row"><button data-op="pulse">Pulse</button><button data-op="hold">Hold</button><button data-op="silence">Silence</button><button data-op="restore">Restore</button></div></div><div id="group-legend" class="group-legend" aria-label="Anatomical groups rendered"></div></section>
<section class="card roam-hud" id="roam-hud" data-panel="roam" hidden><div class="panel-head"><span class="panel-title">Free Roam</span><span class="panel-meta" id="roam-level">LEVEL —</span></div><div class="roam-stats"><div><span>BEACONS / MIN</span><strong id="roam-beacons">—</strong></div><div><span>COLLISIONS / MIN</span><strong id="roam-collisions">—</strong></div><div><span>THREATS DODGED</span><strong id="roam-dodged">—</strong></div><div><span>THREATS HIT</span><strong id="roam-hit">—</strong></div><div><span>CELLS VISITED</span><strong id="roam-cells">—</strong></div></div><div class="roam-log" id="roam-log" aria-label="Free roam event log"></div></section>
<section class="card signals" data-panel="signals" hidden><div class="panel-head"><span class="panel-title">Signals &amp; Controls</span><span class="panel-meta" id="episode">EPISODE 0</span></div><div class="signal-grid"><div><h3>SENSORY CURRENT</h3><div id="cues" class="meters"></div></div><div><h3>NEURAL READOUT</h3><div id="readouts" class="meters"></div></div><div><h3>ACTUAL / COMMANDED RPM</h3><div id="motors" class="meters"></div></div><div><h3>COMPUTE BUDGET</h3><div id="budget" class="meters"></div><p class="outcome" id="budget-note">—</p></div></div><div class="controls"><div><h3>EXPERIMENT</h3><div class="button-row"><button id="pause" class="primary">Pause</button><button id="reset">Reset trial</button></div></div><div><h3>VISUAL TARGET</h3><div class="button-row"><button data-target="left">Left</button><button data-target="center">Center</button><button data-target="right">Right</button></div></div><div><h3>OBSTACLE</h3><div class="button-row"><button id="loom">Place ahead</button><button id="clear">Move aside</button></div></div></div><div class="notes"><span id="command">Motion command: —</span><span id="error">Waiting for the local Rust + MuJoCo service.</span></div></section>
</div>
</div>
<div class="drawer-rail" id="drawer-rail">
<button class="drawer-collapse" id="drawer-collapse" aria-label="Toggle panel drawer" title="Toggle panel"><i>‹</i></button>
<button data-tab="replay" class="tab-btn active">Trials</button>
<button data-tab="brain" class="tab-btn">Brain</button>
<button data-tab="roam" class="tab-btn" id="roam-tab" hidden>Roam</button>
<button data-tab="signals" class="tab-btn">Signals</button>
</div>`;
}
